#!/usr/local/bin/python3

import sys
import os
import shutil
import tarfile
import subprocess
import glob
import datetime
import re

TMP_DIR = "./msdx_tmp"

args = sys.argv

def extract_sd(sd_file):
    if not [ os.path.exists(sd_file) ]:
        sys.exit("support dump file " + sd_file + "does not exists")
    
    if os.path.exists(TMP_DIR):
        shutil.rmtree(TMP_DIR)
    
    tar = tarfile.open(sd_file)
    tar.extractall(path=TMP_DIR)
    tar.close()
    
    dir_name = os.listdir(TMP_DIR)[0]
    print(dir_name)
    
    file_name = ""
    
    sd_meta = ['ls', '-l', TMP_DIR]
    res = subprocess.check_output(sd_meta).split()
    sd_time = res[7].decode('utf-8') + "-" + res[8].decode('utf-8') + "-" + res[9].decode('utf-8').replace(":", "")
    
    with open(TMP_DIR + "/" + dir_name + "/hostname") as f:
        s = f.read().rstrip()
        hostname = s
        print(hostname)
 
    working_dir = hostname + "-" + sd_time
    os.rename(TMP_DIR + "/" + dir_name, working_dir)
    shutil.rmtree(TMP_DIR)

    return working_dir


def check_logs(working_dir):
    format_A = '%Y-%m-%d %H:%M:%S,%f'
    format_B = '%Y-%m-%dT%H:%M:%S,%f'
    logs =       {"mfs":"mapr-logs/mfs.log-3*", "warden":"mapr-logs/warden.log*",
                  "cldb":"mapr-logs/cldb.log*", "nfs":"mapr-logs/nfsserver.log*",
                  "nodemanager":"hadoop-2.7.0-logs/yarn-mapr-nodemanager*.log*","resourcemanager":"hadoop-2.7.0-logs/yarn-mapr-resourcemanager*.log*",
                  "hivemeta":"hive-2.1/mapr/mapr-metastore-*", "hs2":"hive-2.1/mapr/mapr-hiveserver2-*"}
    start_logs = {"os":"Initializing cgroup subsys cpuset", "mfs":"Starting fileserver", "warden":"My pid",
                  "cldb":"CLDBInit: Start CLDBServer", "nfs":"NFS server starting",
                  "nodemanager":"NodeManager: STARTUP_MSG:", "resourcemanager":"ResourceManager: STARTUP_MSG:",
                  "hivemeta":"Starting hive metastore on port", "hs2":"HiveServer2: Starting HiveServer2"}
    end_logs =   {"os":"Stopping Timers", "warden":"ShutdownHook completed", "mfs":"Shutdown ctx",
                  "cldb":"CLDB ShutDown Hook called", "nodemanager":"NodeManager: SHUTDOWN_MSG:",
                  "hivemeta":"HiveMetaStore: SHUTDOWN_MSG:", "hs2":"HiveServer2: SHUTDOWN_MSG"}
    time_format = {"mfs" : format_A, "warden":format_A, "cldb":format_A,
                   "nfs":format_A, "nodemanager":format_A,"resourcemanager":format_A,
                   "hivemeta":format_B, "hs2":format_B}
    cosmetics   = {"warden":"warden",
                   "cldb":"\tcldb", "mfs":"\tmfs",
                   "nodemanager":"\t\tnodemanager", "resourcemanager":"\t\tresourcemanager", "nfs":"\t\tnfs",
                   "hivemeta":"\t\t\thivemeta", "hs2":"\t\t\ths2"}
    errors = {}
    fatal  = {}
    event_record = {}

    for k,v in logs.items():
        err_counter = 0
        fatal_counter = 0
        for filename in glob.glob(working_dir + "/logs/" + v):
            msdx_print(filename)
            f = open(filename, "r")
            lines = f.readlines()
            for line in lines:
                if line.find('ERROR') != -1:
                    err_counter += 1
                if line.find('FATAL') != -1:
                    fatal_counter += 1
                if line.find(start_logs[k]) != -1:
                    try:
                        event_record[datetime.datetime.strptime(line[0:23], time_format[k])] = "start " + cosmetics[k]
                    except:
                        print("datetime error:", line)
                if k in end_logs and line.find(end_logs[k]) != -1:
                    try:
                        event_record[datetime.datetime.strptime(line[0:23], time_format[k])] = "end   " + cosmetics[k]
                    except:
                        print("datetime error:", line)
                    
            f.close()
            errors[k] = err_counter
            fatal[k]  = fatal_counter
    
    for k,v in errors.items():
        msdx_print(k + "\t\t\t ERROR:" + str(v) + ", FATAL:" + str(fatal[k]))
    for k,v in sorted(event_record.items()):
        msdx_print(str(k) + " " + v)


def check_ifconfig(working_dir):
    f = open(working_dir + "/system_info/ifconfig_a", "r")
    lines = f.readlines()
    for line in lines:
        if line.find('dropped') != -1:
            items = re.split(" +", line.rstrip())
            if items[1] == 'TX':
                if items[3] != '0' or items[5] != '0' or items[7] != '0' or items[9] != '0' or items[11] != '0':
                    msdx_print ("Some errors detected : " + line.rstrip())
            else:
                if items[3] != '0' or items[5] != '0' or items[7] != '0' or items[9] != '0':
                    msdx_print ("Some errors detected : " + line.rstrip())


def msdx_print(s):
    msdx_f.write(s + "\n")
    print(s)

working_dir = extract_sd(args[1])
msdx_f = open(working_dir + "/msdx.txt", mode="w")
check_logs(working_dir)
check_ifconfig(working_dir)
msdx_f.close()
print("Check output in " + working_dir + "/msdx.txt")
